//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostManIslemleri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrunSatisDBEntities : DbContext
    {
        public UrunSatisDBEntities()
            : base("name=UrunSatisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TKategori> TKategori { get; set; }
        public virtual DbSet<TMusteri> TMusteri { get; set; }
        public virtual DbSet<TSepet> TSepet { get; set; }
        public virtual DbSet<TUrun> TUrun { get; set; }
    }
}
